### ISSUE TITLE
Paige's Tasks

### ISSUE THREAD

**Issue by paigesmith3794** [rasenin/Project1#10]
## User Story 1
As a user, I want to be able to input search a specific word, so that I can find a specific reminder when I have many reminders saved.

## Acceptance Criteria 1
- [ ] index.html has a search bar feature
- [ ] index.html has a search button
- [ ] javascript has on click functions
- [ ] javascript allows this feature to function (not sure how yet)

## User Story 2
As a user, I want to be able to click the buttons on the website and have them function properly, so that I can add reminders to my to-do lists.

## Acceptance Criteria 2
- [ ] javascript is linked to html 
- [ ] javascript has on click functions
- [ ] javascript on click functions are linked to the correct buttons
- [ ] The buttons direct you to what you want them to do
- [ ] Roman links the data to firebase

## Task 3
Link the "features.html", "sign up.html", "log in.html" files to the "index.html" tag, so that when the user clicks on each section of the nav bar called feature, sign up, and log in, then it will take them to a new webpage
- [x] Link the "features.html" href in index.html
- [x] Link the "sign up.html" href in index.html
- [x] Link the "log in.html" href in index.html

**Comment by captainalan** [comment]
### User Story 1
User input is messy—while users may *think* they only want to enter a specific word to search, be prepared to deal with messy user input like multi-word **search queries**.

### User Story 2
What functionality do you want to have buttons for? For example, you may want options to create, update, and delete reminder items; most users do not desire more buttons (think: Apple, Android, getting rid of buttons vs Blackberries with lots of buttons)—rather, they want it to be easy to do what they want
