### ISSUE TITLE
Loren's Task List (UI)

### ISSUE THREAD

**Issue by viveleloren** [rasenin/Project1#9]
**USER INTERFACE TASK LIST**

- [x] Confirm Feedback for UI direction

- [x] Verify Webpage Attributes

- [x] Rough Draft of Webpage Layout

- [x] Pseudo-Code Elements

- [ ] Initial Functionality Testing

- [ ] Modify Nav Bar on Each Page to Properly Reflect the current page.

- [ ] Complete Features Hero Images

- [ ] Fine Tune No-Tify page

- [ ] 

- [ ]
